#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#


{{- $serviceMesh := include "eric-eo-evnfm.service-mesh-enabled" . | trim -}}
{{- $serviceMeshIngress := include "eric-eo-evnfm.service-mesh-ingress-enabled" . | trim -}}
{{- if and (eq $serviceMesh "true") (eq $serviceMeshIngress "true") }}
{{- if index .Values "global" "geo-redundancy" "enabled" }}
{{- if eq (include "eric-eo-evnfm.global-container-registry.enabled" .) "true" }}
{{- if index .Values "eric-lcm-container-registry" "ingress" "enabled" }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ template "eric-eo-evnfm.name" . }}-global-lcm-container-registry-gateway
  labels:
{{ include "eric-lcm-container-registry.labels" . | indent 4 }}
  annotations:
    ericsson.com/product-name: "Container Registry"
    ericsson.com/product-number: "CXC 201 1698"
    ericsson.com/product-revision: {{ regexReplaceAll "(.*)[+-].*" .Chart.Version "${1}" | quote }}
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
{{- if index .Values "eric-lcm-container-registry" "ingress" "annotations" }}
{{ toYaml (index .Values "eric-lcm-container-registry" "ingress" "annotations") | indent 4 }}
{{- end }}
spec:
  selector:
    app: service-mesh-ingress-gateway
  servers:
  - port:
      number: 80
      name: http-global-registry-chart
      protocol: HTTP
    hosts:
      - {{ index .Values "eric-global-lcm-container-registry" "hostname" | quote }}
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      name: https-global-registry-chart
      number: 443
      protocol: HTTPS
    hosts:
      - {{ index .Values "eric-global-lcm-container-registry" "hostname" | quote }}
    tls:
      mode: SIMPLE
      credentialName: global-registry-tls-secret
{{- end }}
{{- end }}
{{- end }}
{{- end }}