#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

global:
  hosts:
    vnfm: ""
  registry:
    url: ""
    username: ""
    password: ""
  support:
    ipv6:
      enabled: false
  timezone: UTC
  createClusterRoles: true

services:
  onboarding:
    enabled: true

eric-am-common-wfs:
  helm:
    url: ""
  dockerRegistry:
    secret: null

eric-lcm-container-registry:
  enabled: true
  ingress:
    hostname: ""

eric-lcm-helm-chart-registry:
  ingress:
    enabled: false
  env:
    secret:
      BASIC_AUTH_USER: ""
      BASIC_AUTH_PASS: ""

eric-vnfm-orchestrator-service:
  oss:
    topology:
      secretName: null
  smallstack:
    application: true