#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

global:
  hosts:
    so: ""
    sdd: ""
    iam: ""
    wano: ""
    vnfm: ""
    pf: ""
    uds: ""
  registry:
    # If deploying from the director node on a CCD environment, the url can be retrieved using:
    # kubectl get ingress eric-lcm-container-registry-ingress -n kube-system -o jsonpath="{.spec.tls[*].hosts[0]}"; echo
    url: "armdocker.rnd.ericsson.se"
    # kubectl get secrets cr-registry-credentials -n kube-system -o jsonpath="{.data.custom-user}" | base64 -d; echo
    username: ""
    # kubectl get secrets cr-registry-credentials -n kube-system -o jsonpath="{.data.custom-pass}" | base64 -d; echo
    password: ""
    pullSecret: "docker-reg-creds"
  support:
    ipv6:
      enabled: false
  timezone: UTC

tags:
  eoEvnfm: true
  eoVmvnfm: false
  eoSo: false
  eoWano: false

eric-sec-access-mgmt:
  ingress:
    hostname: ""

# Fill only if deploying EO Container VNFM (EO EVNFM)
eric-eo-evnfm:
  eric-lcm-container-registry:
    ingress:
      hostname: ""
    registry:
      volumes:
        data:
          size: "50Gi"
    brAgent:
      enabled: false
  eric-lcm-helm-chart-registry:
    ingress:
      enabled: false
      hostname: ""
  application-manager-postgres:
    brAgent:
      enabled: false
    highAvailability:
      replicaCount: 1
  eric-eo-evnfm-mb:
    enabled: true
  eric-am-common-wfs:
    camunda:
      historyTimeToLive: 1

idam-database-pg:
  highAvailability:
    replicaCount: 1
  brAgent:
    enabled: false

eric-eo-eai-database-pg:
  brAgent:
    enabled: false

backup-controller:
  enabled: false

eric-eo-usermgmt:
  replicas: 0

eric-eo-usermgmt-ui:
  replicas: 0

eric-eo-evnfm-nbi:
  replicaCount: 1
  eric-evnfm-rbac:
    defaultUser:
      username: vnfm-user
      password: DefaultP12345!

logging:
  enabled: false

eric-pm-server:
  enabled: false
